//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magic8BallApp.Magic8BallService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Magic8BallService.IMagic8Ball")]
    public interface IMagic8Ball {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagic8Ball/Shake", ReplyAction="http://tempuri.org/IMagic8Ball/ShakeResponse")]
        string Shake(string question);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMagic8BallChannel : Magic8BallApp.Magic8BallService.IMagic8Ball, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Magic8BallClient : System.ServiceModel.ClientBase<Magic8BallApp.Magic8BallService.IMagic8Ball>, Magic8BallApp.Magic8BallService.IMagic8Ball {
        
        public Magic8BallClient() {
        }
        
        public Magic8BallClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Magic8BallClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Magic8BallClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Magic8BallClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Shake(string question) {
            return base.Channel.Shake(question);
        }
    }
}
